### ISSUE TITLE
"reminder is not enabled on this weekday" triggers makes Toggl Desktop Crash

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1900]
User reports that they switched accounts and that's what made the app crash. The real issue could be with tracking reminder.

It seems that when reminder is triggered on a day that it's not enabled it keeps checking almost every second.

```
2016-05-08 12:26:14.937 [20768 3]:context:D:reminder is not enabled on this weekday
2016-05-08 12:26:15.947 [20768 3]:context:D:reminder is not enabled on this weekday
2016-05-08 12:26:16.977 [20768 3]:context:D:reminder is not enabled on this weekday
2016-05-08 12:26:18.007 [20768 3]:context:D:reminder is not enabled on this weekday
2016-05-08 12:26:19.037 [20768 3]:context:D:reminder is not enabled on this weekday
2016-05-08 12:26:20.048 [20768 3]:context:D:reminder is not enabled on this weekday
```

It should detect when the next enabled day is and not start checking once an hour or longer.

Error Stack:

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Full log in case 282316

**Comment by IndrekV** [comment]
Out of date.

**Comment by skel35** [comment]
not sure if it caused any crash, but I've still seen the "reminder is not enabled on this weekday" being printed to the log every second somewhere recently, so I'd keep this one open.
