### ISSUE TITLE
Windows app crashing when user clicks on Load more

### ISSUE THREAD

**Issue by zdericnina** [toggl-open-source/toggldesktop#4085]
### 💻 Environment

Platform:  Windows
OS Version:  Windows 10
Toggl Version:  7.5.119

### 🐞 Actual behavior

Clicking on a Load more button first freezes the app and then it crashes

### 💯 Expected behavior

Clicking on Load more should load more time entries

### 📦 Additional info

User tried clearing the cache couple of times, updated to beta but nothing helped so far. He recently modified some Projects via the web app (e.g. assigning Clients) before the app started to crash. [Error entry from the log](https://app.intercom.com/a/apps/ayixs927/inbox/conversations/27124893511)

**Comment by Troi7** [comment]
Same problem on Windows 10 with versions:
beta 7.5.454
dev 7.5.461

Reinstall with delete local data didn't help. Clearing cache didn't help.

```
2022-11-01 18:54:07.023 [52756 0]:toggl_api:D:Notifying bugsnag: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at TogglDesktop.TimeEntryList.SetDayHeaderViewModels(DayHeaderViewModel[] dayHeaderViewModels)
   at TogglDesktop.TimerEntryListView.fillTimeEntryList(List`1 list)
   at TogglDesktop.TimerEntryListView.onTimeEntryList(Boolean open, List`1 list, Boolean showLoadMoreButton)
```

**Comment by Troi7** [comment]
Problem remains same in current dev 7.5.463 version.

`2022-12-01 11:37:33.897 [44776 0]:toggl_api:D:Notifying bugsnag: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at TogglDesktop.TimeEntryList.SetDayHeaderViewModels(DayHeaderViewModel[] dayHeaderViewModels)
   at TogglDesktop.TimerEntryListView.fillTimeEntryList(List`1 list)
   at TogglDesktop.TimerEntryListView.onTimeEntryList(Boolean open, List`1 list, Boolean showLoadMoreButton)`
