### ISSUE TITLE
Segfault in libQt5WebEngineCore in Flatpak, on Fedora

### ISSUE THREAD

**Issue by jbirch** [toggl-open-source/toggldesktop#4098]
### 💻 Environment
Platform: Linux
OS Version: Fedora 32
Toggl Version: 7.4.528

Other fun things:
* Kernel 5.6.13
* Gnome 3.36.2
* X11 1.20.8
* NVidia driver 440.82
* Flatpak 1.6.3

Flatpak-ery:
```
$ flatpak list
Name                               Application ID                                            Version        Branch      Installation
TogglDesktop                       com.toggl.TogglDesktop                                                   stable      system
default                            org.freedesktop.Platform.GL.default                                      19.08       system
nvidia-440-82                      org.freedesktop.Platform.GL.nvidia-440-82                                1.4         system
html5-codecs                       org.freedesktop.Platform.html5-codecs                                    18.08       system
openh264                           org.freedesktop.Platform.openh264                                        2.0         system
Freedesktop SDK                    org.freedesktop.Sdk                                       19.08.10       19.08       system
Adwaita theme                      org.kde.KStyle.Adwaita                                                   5.12        system
KDE Application Platform           org.kde.Platform                                                         5.12        system
QGnomePlatform                     org.kde.PlatformTheme.QGnomePlatform                                     5.12        system
KDE Software Development Kit       org.kde.Sdk                                                              5.12        system
QGnomePlatform-decoration          org.kde.WaylandDecoration.QGnomePlatform-decoration                      5.12        system

```

### 🐞 Actual behavior
When logging in using Google, after inputting my password, if I click next, the application segfaults.

### 💯 Expected behavior
I expect to progress to the 2fa Google screen.

### 🔨 Steps to reproduce
1. Install TogglDesktop using the flatpakref available on the website:
```
$ flatpak install Downloads/com.toggl.TogglDesktop.flatpakref
```
2. Run TogglDesktop via FlatPak
3. Select "Log in with Google Account" — the window opens successfully.
4. Enter your email and click "Next"
5. Enter your password and click "Next" — the google "Something is happening" blue bar at the top is moving fine.
6. Presumably on response coming back, the application Segfaults.

### 📦 Additional info
I'm fairly certain this just has to do with the version of qt webengine. If I install the KDE SDK in Flatpak, I'm able to run the application under GDB:

```
Thread 1 "TogglDesktop" received signal SIGSEGV, Segmentation fault.
0x00007ffff11bc9e8 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
(gdb) bt full
#0  0x00007ffff11bc9e8 in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#1  0x00007ffff11babfb in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5

[ ... trimmed ... ]

#19 0x00007fffef702df8 in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
#20 0x00007ffff6a8fddb in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff74d55c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff74dca60 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00005555555a3672 in TogglApplication::notify(QObject*, QEvent*) ()
#24 0x00007ffff6a65539 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff6a68587 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff6ab9c03 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fffec02f4ae in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fffec02f748 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffec02f7e0 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6ab9213 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff6a6414b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff6a6c122 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x0000555555593e71 in main ()
```

If I install qt webengine natively (`$ sudo dnf install qt5-qtwebengine` for Fedora) and then force manually make the other Flatpak-available shared objects available, it works:

```
 /var/lib/flatpak/app/com.toggl.TogglDesktop/current/active/files$ LD_PRELOAD=./lib/libTogglDesktopLibrary.so:./lib/libOAuth2.so:./lib/libQxt.so:./lib/libBugsnag.so:./lib/libjsoncpp.so:./lib/libLua.so:./lib/libPocoDataSQLite.so:./lib/libPocoNetSSL.so:./lib/libPocoData.so:./lib/libPocoCrypto.so:./lib/libPocoNet.so:./lib/libPocoUtil.so:./lib/libPocoFoundation.so ./bin/TogglDesktop
```

With this arrangement (IE not linking against the flatpak-provided `libQt5WebEngine.so.5`, but instead linking against the native `/lib64/libQt5WebEngine.so.5`), everything works as expected — clicking "Next" on the password screen proceeds to ask about my 2fa details.

The natively installed version of qt webengine is 5.13.2. The flatpak provided version is 5.12.7. I'm unsure if the solution is in the version difference, or something missing from the flatpak-provided qt deps.

**Comment by MartinBriza** [comment]
Hmh, thanks for the report. This is not ideal. I'll work on removing the QtWebEngine dependency entirely, so we don't suffer from these sorts of compatibility issues anymore going further.

**Comment by MartinBriza** [comment]
Anyway FWIW I'm developing the app on Fedora and as far as I recall it was always working for me. I'd love to test it now on Fedora 32 but my internet conections is extremely shoddy at this moment and I will probably never be able to download it along with the KDE runtimes so I'll look into it later.
